import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { Finder } from "@/components/finder/Finder";
import { ComparisonPage, DestinationPage, FixtureNotice, MethodNote, MonthPage, RankingPage } from "@/components/hiking/Pages";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { getAllDestinations, getComparison, getComparisonIndex, getDestination, getRanking, getSearchIndex } from "@/lib/data/load";
import { comparePath, destinationPath, locales, monthName, monthNumber, monthSlug, rankingPath, routes } from "@/lib/i18n/config";
import { routeCatalog } from "@/lib/seo/route-catalog";
import type { Locale } from "@/lib/data/types";

type Params = Promise<{locale:string;segments?:string[]}>;
export const dynamicParams = false;
export const dynamic = "force-static";
export function generateStaticParams(){return routeCatalog().filter((route)=>route.segments.length>0);}

function pageTitle(locale:Locale,segments:string[]) {
  if(!segments.length) return locale === "de" ? "Finde deine beste Wanderzeit" : "Find your best hiking season";
  if(segments[0]===routes.destination[locale]) { const destination=getDestination(segments[1]); const month=segments[2]&&monthNumber(segments[2],locale); return destination ? month ? `${destination.name} · ${monthName(month,locale)}` : destination.name : "BestTimeToHike"; }
  if(segments[0]===routes.compare[locale]) return segments[1]?.replaceAll("-"," ") ?? "Compare";
  return segments.at(-1)?.replaceAll("-"," ") ?? "BestTimeToHike";
}

export async function generateMetadata({params}:{params:Params}):Promise<Metadata>{const {locale:raw,segments=[]}=await params; if(!locales.includes(raw as Locale)) return {}; const locale=raw as Locale; const base=process.env.NEXT_PUBLIC_APP_URL ?? "https://best-time-to-hike.pages.dev"; const path=`/${locale}/${segments.join("/")}`; const other=locale==="en"?"de":"en"; return {title:pageTitle(locale,segments),alternates:{canonical:`${base}${path}`,languages:{[locale]:`${base}${path}`,[other]:`${base}/${other}`}},robots:{index:process.env.NEXT_PUBLIC_DATA_STATUS==="production",follow:true}};}

function Home({locale}:{locale:Locale}) { const destinations=getAllDestinations(); return <><FixtureNotice locale={locale}/><section className="home-hero"><div className="hero-copy"><span className="eyebrow">{locale === "de" ? "Wohin. Wann. Warum." : "Where. When. Why."}</span><h1>{locale === "de" ? "Finde die beste Zeit und den besten Ort für deine nächste Wanderung." : "Find the best time and place for your next hike."}</h1><p>{locale === "de" ? "Monatliche Wanderwerte verbinden Klima, Höhe, Schnee, Hitze, Wind und Tageslicht." : "Monthly hiking scores connect climate, elevation, snow, heat, wind and daylight."}</p><div className="hero-actions"><Link className="button" href={`/${locale}/finder`}>{locale === "de" ? "Finder starten" : "Start exploring"}</Link><Link className="text-link light" href={`/${locale}/${routes.methodology[locale]}`}>{locale === "de" ? "Methodik verstehen →" : "See the methodology →"}</Link></div></div><div className="hero-visual"><div className="sun"/><div className="mountain mountain-back"/><div className="mountain mountain-front"/><span>47° 12′ N<br/>11° 23′ E</span></div></section><section className="finder-wrap"><div className="section-heading"><div><span className="eyebrow">{locale === "de" ? "Entscheidungs-Finder" : "Decision finder"}</span><h2>{locale === "de" ? "Deine Bedingungen. Deine besten Treffer." : "Your conditions. Your best matches."}</h2></div></div><Finder destinations={getSearchIndex()} locale={locale} compact/></section><section className="content-section"><div className="section-heading"><div><span className="eyebrow">{locale === "de" ? "Ziele entdecken" : "Explore destinations"}</span><h2>{locale === "de" ? "Fünf Landschaften, zwölf Monate" : "Five landscapes, twelve months"}</h2></div></div><div className="card-grid">{destinations.map((destination)=><Link className="destination-card" href={destinationPath(locale,destination.slug)} key={destination.slug}><span>{destination.countryCode} · {destination.region}</span><h3>{destination.name}</h3><p>{destination.bestMonths.map((month)=>monthName(month,locale)).join(" · ")}</p><strong>{locale === "de" ? "Saison ansehen →" : "See the season →"}</strong></Link>)}</div></section><MethodNote locale={locale}/></> }

function InformationPage({locale,kind}:{locale:Locale;kind:string}) { const content:Record<string,{en:[string,string[]];de:[string,string[]]}>= {methodology:{en:["How the hiking score works",["We combine temperature comfort (30%), precipitation (20%), snow (20%), heat stress (10%), wind (10%) and daylight (10%).","The intended production dataset uses ERA5-Land for 1991–2020, Copernicus DEM GLO-30 and deterministic astronomical daylight. This deployed demo uses synthetic fixtures only.","Scores describe regional, historical suitability. They are not forecasts, trail-condition reports or safety advice."]],de:["So funktioniert der Wanderwert",["Wir kombinieren Temperaturkomfort (30 %), Niederschlag (20 %), Schnee (20 %), Hitzestress (10 %), Wind (10 %) und Tageslicht (10 %).","Der vorgesehene Produktionsdatensatz nutzt ERA5-Land 1991–2020, Copernicus DEM GLO-30 und deterministisch berechnetes Tageslicht. Diese Demo nutzt nur synthetische Fixtures.","Die Werte beschreiben regionale historische Eignung. Sie sind keine Vorhersage, kein Wegzustandsbericht und keine Sicherheitsberatung."]]},about:{en:["A clearer way to choose a hiking season",["BestTimeToHike is a static, transparent decision engine—not a navigation app. Every recommendation is designed to be traceable to versioned data and scoring rules."]],de:["Wandersaisons klarer auswählen",["BestTimeToHike ist eine statische, transparente Entscheidungshilfe – keine Navigations-App. Jede Empfehlung soll auf versionierte Daten und Regeln zurückführbar sein."]]},privacy:{en:["Privacy",["This static demo has no accounts, analytics, cookies or runtime database. Cloudflare may process standard request metadata when serving files."]],de:["Datenschutz",["Diese statische Demo hat keine Konten, Analysen, Cookies oder Laufzeitdatenbank. Cloudflare kann beim Ausliefern der Dateien übliche Request-Metadaten verarbeiten."]]},imprint:{en:["Imprint",["Project prototype. Operator contact details must be added before a commercial production launch."]],de:["Impressum",["Projektprototyp. Vor einem kommerziellen Produktionsstart müssen die Kontaktdaten des Betreibers ergänzt werden."]]},credits:{en:["Image credits",["This demo uses CSS-generated topographic artwork and no third-party photography."]],de:["Bildnachweis",["Diese Demo verwendet CSS-generierte topografische Gestaltung und keine Fotos Dritter."]]}}; const data=content[kind]?.[locale]; if(!data) notFound(); return <><section className="page-intro prose-intro"><span className="eyebrow">BestTimeToHike</span><h1>{data[0]}</h1>{data[1].map((paragraph)=><p key={paragraph}>{paragraph}</p>)}</section>{kind==="methodology"&&<section className="weight-diagram">{[["Temperature","30%"],["Precipitation","20%"],["Snow","20%"],["Heat","10%"],["Wind","10%"],["Daylight","10%"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>}<MethodNote locale={locale}/></> }

export default async function LocalizedPage({params}:{params:Params}) { const {locale:raw,segments=[]}=await params; if(!locales.includes(raw as Locale)) notFound(); const locale=raw as Locale; let content:React.ReactNode;
  if(!segments.length) content=<Home locale={locale}/>;
  else if(segments[0]==="finder"&&segments.length===1) content=<><FixtureNotice locale={locale}/><section className="page-intro"><span className="eyebrow">{locale === "de" ? "Persönlicher Match" : "Personal match"}</span><h1>{locale === "de" ? "Finde deine Wandersaison" : "Find your hiking season"}</h1><p>{locale === "de" ? "Deine Präferenzen verändern den veröffentlichten Wanderwert nicht – sie erzeugen einen separaten Match-Wert." : "Your preferences never overwrite the published hiking score—they produce a separate match score."}</p></section><div className="finder-page"><Finder destinations={getSearchIndex()} locale={locale}/></div></>;
  else if(segments[0]===routes.destination[locale]&&segments[1]) { const destination=getDestination(segments[1]); if(!destination) notFound(); const month=segments[2]&&monthNumber(segments[2],locale); content=month?<MonthPage destination={destination} month={month} locale={locale}/>:<DestinationPage destination={destination} locale={locale}/>; }
  else if(segments[0]===routes.rankings[locale]) { const slug=segments.at(-1)!; const month=monthNumber(slug,locale); if(!month) notFound(); content=<RankingPage ranking={getRanking(month)} locale={locale}/>; }
  else if([routes.warm[locale],routes.snowFree[locale],routes.lowRain[locale]].includes(segments[0] as any)) { const month=monthNumber(segments[1],locale); if(!month) notFound(); const theme=segments[0]===routes.warm[locale]?"warm":segments[0]===routes.snowFree[locale]?"snow-free":"low-rain"; const title=locale==="de"?`${theme==="warm"?"Warm wandern":theme==="snow-free"?"Schneefrei wandern":"Wenig Regen"} im ${monthName(month,locale)}`:`${theme==="warm"?"Warm hiking":theme==="snow-free"?"Snow-free hiking":"Low-rain hiking"} in ${monthName(month,locale)}`; content=<RankingPage ranking={getRanking(month,theme)} locale={locale} title={title}/>; }
  else if(segments[0]===routes.compare[locale]&&getComparisonIndex().some((item)=>item.slug===segments[1])) content=<ComparisonPage comparison={getComparison(segments[1])} locale={locale}/>;
  else { const infoEntry=(Object.keys(routes) as Array<keyof typeof routes>).find((key)=>["methodology","about","privacy","imprint","credits"].includes(key)&&routes[key][locale]===segments[0]); if(!infoEntry) notFound(); content=<InformationPage locale={locale} kind={infoEntry}/>; }
  return <><SiteHeader locale={locale}/><main>{content}</main><SiteFooter locale={locale}/></>;
}
