import Link from "next/link";
import type { Comparison, Locale, PublicDestination, Ranking } from "@/lib/data/types";
import { comparePath, destinationPath, monthName, rankingPath } from "@/lib/i18n/config";
import { getDestination, getManifest } from "@/lib/data/load";
import { ScoreRing } from "./ScoreRing";
import { ScoreChart } from "./ScoreChart";
import { ComponentGrid } from "./ComponentGrid";

const copy = {
  en:{score:"Hiking score",confidence:"Data confidence",best:"Best months",elevation:"Elevation view",typical:"Typical historical conditions",why:"Why it scores this way",alternatives:"Similar alternatives",method:"Historical climatology, not a forecast",view:"View month",ranking:"Best hiking destinations",compare:"Side-by-side season guide"},
  de:{score:"Wanderwert",confidence:"Datenvertrauen",best:"Beste Monate",elevation:"Höhenvergleich",typical:"Typische historische Bedingungen",why:"Warum dieser Wert",alternatives:"Ähnliche Alternativen",method:"Historische Klimatologie, keine Vorhersage",view:"Monat ansehen",ranking:"Beste Wanderziele",compare:"Saisonaler Direktvergleich"}
};

export function FixtureNotice({locale}:{locale:Locale}) {
  const realData = getManifest().datasetStatus !== "fixture";
  return <div className="fixture-notice"><strong>{realData ? (locale === "de" ? "Real-Data-Beta" : "Real-data beta") : (locale === "de" ? "Demo-Datensatz" : "Demo dataset")}</strong><span>{realData ? (locale === "de" ? "ERA5-Land-Klimanormal 1991–2020 für einen repräsentativen Modell-Gitterpunkt. Keine Vorhersage und kein Ersatz für aktuelle Weg- oder Sicherheitsinformationen." : "ERA5-Land 1991–2020 climate normal for one representative model-grid cell. Not a forecast or a substitute for current trail and safety information.") : (locale === "de" ? "Diese Version nutzt klar gekennzeichnete synthetische Fixtures. Nicht für Reise- oder Sicherheitsentscheidungen." : "This build uses clearly labeled synthetic fixtures. Do not use it for travel or safety decisions.")}</span></div>;
}

function RecommendationReviewNotice({locale, destination}:{locale:Locale; destination:PublicDestination}) {
  if (!destination.recommendationHoldReason) return null;
  return <aside className="method-note recommendation-review" role="status"><span>⚠</span><div><strong>{locale === "de" ? "Ziel wird wissenschaftlich geprüft" : "Destination under scientific review"}</strong><p>{locale === "de" ? "Für dieses Ziel werden derzeit keine Wanderwert- oder besten-Monate-Empfehlungen angezeigt. Die ausgewählte repräsentative Gitterzelle weist ganzjährig persistierenden Schnee auf." : "No hiking score or best-month recommendation is shown for this destination yet. The selected representative grid cell has persistent snow in every month."}</p><p>{locale === "de" ? `Ausgewählte Zelle: ${destination.representativeCell.lat}, ${destination.representativeCell.lon} · Modellhöhe ${destination.representativeCell.modelElevationM} m.` : `Selected cell: ${destination.representativeCell.lat}, ${destination.representativeCell.lon} · model elevation ${destination.representativeCell.modelElevationM} m.`}</p></div></aside>;
}

export function DestinationPage({destination,locale}:{destination:PublicDestination;locale:Locale}) {
  const c=copy[locale]; const held=destination.recommendationHoldReason === "persistent-snow"; const unavailable=!destination.recommendationEligible; const hasEligibleMonth=destination.months.some((month)=>month.recommendationEligible); const peak=Math.max(0,...destination.months.flatMap((month)=>month.overallScore===null?[]:[month.overallScore]));
  return <>
    <FixtureNotice locale={locale}/>
    <section className="destination-hero"><div className="eyebrow">{destination.countryName} · {destination.region}</div><div className="destination-title"><div><h1>{held ? (locale === "de" ? `Datenprüfung: ${destination.name}` : `Data review: ${destination.name}`) : unavailable ? (locale === "de" ? `Keine Empfehlung: ${destination.name}` : `No recommendation: ${destination.name}`) : (locale === "de" ? `Beste Wanderzeit für ${destination.name}` : `Best time to hike ${destination.name}`)} </h1><p>{locale === "de" ? `Ausgewählte repräsentative ERA5-Land-Gitterzelle auf etwa ${destination.representativeCell.modelElevationM} Metern; keine Aussage über jede Route der gesamten Region.` : `Selected representative ERA5-Land grid cell at about ${destination.representativeCell.modelElevationM} metres; not a claim about every route across the region.`}</p></div>{unavailable ? null : <ScoreRing score={peak}/>}</div><div className="topo-lines" aria-hidden="true"/></section>
    <RecommendationReviewNotice locale={locale} destination={destination}/>
    {!unavailable ? <section className="content-section"><div className="section-heading"><div><span className="eyebrow">12 {locale === "de" ? "Monate" : "months"}</span><h2>{c.best}</h2></div><p>{destination.bestMonths.map((month)=>monthName(month,locale)).join(" · ")}</p></div><ScoreChart months={destination.months} locale={locale} slug={destination.slug}/></section> : null}
    {unavailable && !hasEligibleMonth && !held ? <aside className="method-note recommendation-review" role="status"><span>⚠</span><div><strong>{locale === "de" ? "Keine Monate erfüllen den Empfehlungstest" : "No month passes the recommendation gate"}</strong><p>{locale === "de" ? "Für dieses Ziel liegt in keinem Monat ein vollständig ausreichender kritischer Komponentenwert vor. Deshalb werden keine besten Monate oder Ranglistenempfehlungen angezeigt." : "No month for this destination clears all critical component thresholds. Best months and ranking recommendations are therefore withheld."}</p></div></aside> : null}
    <section className="content-section split"><div><span className="eyebrow">{unavailable ? (locale === "de" ? "Provenienz" : "Provenance") : c.elevation}</span><h2>{unavailable ? (locale === "de" ? "Ausgewählte repräsentative Zelle" : "Selected representative cell") : (locale === "de" ? "Ein reproduzierbarer Referenzpunkt" : "One reproducible reference point")}</h2><p>{held ? (locale === "de" ? "Diese Detailseite bleibt als Prüfseite erreichbar. Wegen des persistierenden Schneesignals werden hier keine Wanderwerte oder besten Monate behauptet." : "This detail page remains available as a review page. Because of the persistent-snow signal, it makes no hiking-score or best-month claims.") : unavailable ? (locale === "de" ? "Diese Detailseite bleibt für Datenprüfung und Provenienz erreichbar. Da kein Monat den Empfehlungstest erfüllt, werden hier keine Wanderwert- oder besten-Monate-Empfehlungen behauptet." : "This detail page remains available for data review and provenance. Because no month passes the recommendation gate, it makes no hiking-score or best-month claims.") : (locale === "de" ? "Der Monatswert gilt für die ausgewählte repräsentative ERA5-Land-Gitterzelle. Er ist bewusst keine unvalidierte Aussage über jede Route der gesamten Region." : "The monthly value represents the selected representative ERA5-Land grid cell. It deliberately does not pretend to describe every route across the region.")}</p><p>{destination.representativeCell.lat}, {destination.representativeCell.lon} · {destination.representativeCell.modelElevationM} m</p></div><div className="elevation-list">{destination.elevationBands.map((band)=><div key={band.id}><span>{band.id.replaceAll("-"," ")}</span><strong>{band.minM}–{band.maxM} m</strong><small>{Math.round(band.weight*100)}% {locale === "de" ? "Gewicht" : "weight"}</small></div>)}</div></section>
    <section className="content-section"><div className="section-heading"><div><span className="eyebrow">{c.alternatives}</span><h2>{locale === "de" ? "Weiterdenken" : "Keep exploring"}</h2></div></div><div className="card-grid">{destination.alternatives.map((slug)=>{const item=getDestination(slug)!;return <Link className="destination-card" href={destinationPath(locale,slug)} key={slug}><span>{item.countryCode}</span><h3>{item.name}</h3><p>{item.bestMonths.map((month)=>monthName(month,locale)).join(" · ")}</p><strong>{locale === "de" ? "Ziel ansehen →" : "Explore destination →"}</strong></Link>})}</div></section>
    <MethodNote locale={locale}/>
  </>;
}

export function MonthPage({destination,month,locale}:{destination:PublicDestination;month:number;locale:Locale}) {
  const data=destination.months[month-1]; const c=copy[locale]; const previous=month===1?12:month-1; const next=month===12?1:month+1;
  if (destination.recommendationHoldReason === "persistent-snow") return <><FixtureNotice locale={locale}/><section className="page-intro prose-intro"><span className="eyebrow">{destination.name} · {monthName(month,locale)}</span><h1>{locale === "de" ? `Datenprüfung für ${destination.name}` : `Data review for ${destination.name}`}</h1><p>{locale === "de" ? "Diese Monatsroute ist als Provenienzseite erreichbar. Wegen des persistierenden Schneesignals werden kein Wanderwert und keine Empfehlung für diesen Monat angezeigt." : "This month route remains available as a provenance page. Because of the persistent-snow signal, no hiking score or recommendation is shown for this month."}</p><p>{locale === "de" ? `Ausgewählte Zelle: ${destination.representativeCell.lat}, ${destination.representativeCell.lon} · Modellhöhe ${destination.representativeCell.modelElevationM} m.` : `Selected cell: ${destination.representativeCell.lat}, ${destination.representativeCell.lon} · model elevation ${destination.representativeCell.modelElevationM} m.`}</p></section><RecommendationReviewNotice locale={locale} destination={destination}/><MethodNote locale={locale}/></>;
  if (!data || data.overallScore === null || data.confidenceScore === null || data.confidenceLevel === null || data.components === null || data.scoreLevel === null) return <><FixtureNotice locale={locale}/><section className="page-intro prose-intro"><span className="eyebrow">{destination.name} · {monthName(month,locale)}</span><h1>{locale === "de" ? "Datenprüfung" : "Data review"}</h1><p>{locale === "de" ? "Für diesen Monat werden derzeit keine Wanderwertdaten veröffentlicht." : "No hiking score data is currently published for this month."}</p></section><MethodNote locale={locale}/></>;
  return <>
    <FixtureNotice locale={locale}/>
    {!data.recommendationEligible ? <aside className="method-note recommendation-review" role="status"><span>⚠</span><div><strong>{locale === "de" ? "Für Empfehlungen ungeeigneter Monat" : "Not eligible for recommendation"}</strong><p>{locale === "de" ? "Mindestens eine kritische Klima-Komponente liegt bei 20 oder darunter. Der Wert ist deshalb konservativ auf 49/poor begrenzt und dieser Monat erscheint nicht in Ranglisten oder besten Monaten." : "At least one critical climate component is 20 or below. The score is therefore conservatively capped at 49/poor, and this month is excluded from rankings and best-month lists."}</p></div></aside> : null}
    <section className="month-hero"><div><span className="eyebrow">{destination.name} · {monthName(month,locale)}</span><h1>{locale === "de" ? `${destination.name} im ${monthName(month,locale)} erwandern` : `Hiking ${destination.name} in ${monthName(month,locale)}`}</h1><p>{c.method}</p></div><ScoreRing score={data.overallScore}/></section>
    <section className="stats-strip"><div><span>{c.confidence}</span><strong>{data.confidenceScore}%</strong></div><div><span>{locale === "de" ? "Ø Temperatur" : "Mean temperature"}</span><strong>{data.metrics.temperatureHikingMeanC}°C</strong></div><div><span>{locale === "de" ? "Regentage" : "Wet days"}</span><strong>{Math.round(data.metrics.wetDayProbability*100)}%</strong></div><div><span>{locale === "de" ? "Tageslicht" : "Daylight"}</span><strong>{data.metrics.daylightHoursMean}h</strong></div></section>
    <section className="content-section"><div className="section-heading"><div><span className="eyebrow">{c.why}</span><h2>{locale === "de" ? "Sechs Komponenten, ein transparenter Wert" : "Six components, one transparent score"}</h2></div></div><ComponentGrid components={data.components} locale={locale}/></section>
    <section className="content-section"><div className="section-heading"><div><span className="eyebrow">{c.elevation}</span><h2>{destination.elevationBands.length===1 ? (locale === "de" ? "Ausgewählte repräsentative Zelle" : "Selected representative cell") : (locale === "de" ? "Vom Tal bis ins Gebirge" : "From low ground to the mountains")}</h2></div></div><div className="band-table">{data.bands.map((band)=><div key={band.bandId}><div><strong>{band.bandId.replaceAll("-"," ")}</strong><span>{band.targetElevationM} m</span></div><ScoreRing score={band.overallScore ?? 0} size="small"/><div><span>{band.temperatureHikingMeanC}°C</span><small>{Math.round(band.snowDayProbability*100)}% {locale === "de" ? "Schneetage" : "snow days"}</small></div></div>)}</div></section>
    <nav className="month-nav" aria-label={locale === "de" ? "Benachbarte Monate" : "Adjacent months"}><Link href={destinationPath(locale,destination.slug,previous)}>← {monthName(previous,locale)}</Link><Link href={destinationPath(locale,destination.slug)}>{destination.name}</Link><Link href={destinationPath(locale,destination.slug,next)}>{monthName(next,locale)} →</Link></nav>
    <MethodNote locale={locale}/>
  </>;
}

export function RankingPage({ranking,locale,title}:{ranking:Ranking;locale:Locale;title?:string}) {
  return <><FixtureNotice locale={locale}/><section className="page-intro"><span className="eyebrow">{monthName(ranking.month,locale)} · {ranking.theme}</span><h1>{title ?? `${copy[locale].ranking} ${locale === "de" ? "im" : "in"} ${monthName(ranking.month,locale)}`}</h1><p>{locale === "de" ? "Vorsortiert nach Wanderwert, dann Datenvertrauen. Affiliate-Provisionen spielen keine Rolle." : "Pre-ranked by hiking suitability, then confidence. Affiliate economics never influence the order."}</p></section><section className="ranking-list">{ranking.entries.map((entry)=><Link href={destinationPath(locale,entry.slug,ranking.month)} key={entry.slug}><span className="ranking-number">{String(entry.rank).padStart(2,"0")}</span><div><h2>{entry.name}</h2><p>{entry.countryCode} · {entry.tempC}°C · {Math.round(entry.wet*100)}% {locale === "de" ? "Regentage" : "wet days"}</p></div><ScoreRing score={entry.score} size="small"/></Link>)}</section><MethodNote locale={locale}/></>;
}

export function ComparisonPage({comparison,locale}:{comparison:Comparison;locale:Locale}) {
  const first=getDestination(comparison.destinations[0])!; const second=getDestination(comparison.destinations[1])!;
  return <><FixtureNotice locale={locale}/><section className="page-intro"><span className="eyebrow">{copy[locale].compare}</span><h1>{first.name} vs {second.name}</h1><p>{locale === "de" ? "Vergleiche den saisonalen Verlauf – nicht nur einen Jahresdurchschnitt." : "Compare the seasonal rhythm, not just an annual average."}</p></section><section className="comparison-grid"><div className="comparison-head"><strong>{first.name}</strong><span>{locale === "de" ? "Monat" : "Month"}</span><strong>{second.name}</strong></div>{comparison.months.map((item)=><div key={item.month}><span className={item.winner===first.slug?"winner":""}>{item.firstScore ?? "—"}</span><Link href={rankingPath(locale,item.month)}>{monthName(item.month,locale).slice(0,3)}</Link><span className={item.winner===second.slug?"winner":""}>{item.secondScore ?? "—"}</span></div>)}</section><div className="centered-links"><Link className="button secondary" href={destinationPath(locale,first.slug)}>{first.name}</Link><Link className="button secondary" href={destinationPath(locale,second.slug)}>{second.name}</Link></div><MethodNote locale={locale}/></>;
}

export function MethodNote({locale}:{locale:Locale}) { return <aside className="method-note"><span>ⓘ</span><div><strong>{locale === "de" ? "Vor dem Aufbruch prüfen" : "Check before you go"}</strong><p>{locale === "de" ? "BestTimeToHike beschreibt typische historische Bedingungen an einer ausgewählten repräsentativen Modell-Gitterzelle. Der Windwert ist grober 10-m-Gitterwind und keine validierte Aussage über exponierte Wege oder Böen. Prüfe immer aktuelle Wetter-, Weg- und Sicherheitsinformationen." : "BestTimeToHike describes typical historical conditions at one selected representative model-grid cell. Wind is coarse 10 m grid-cell wind, not validated exposed-trail or gust information. Always check current weather, trail, and safety information."}</p></div></aside>; }
