import type { BlogPost } from "@/lib/blog/content";
import { links } from "@/lib/i18n/links";
import { evidence } from "./shared";

export const daylightAndHikingSeason: BlogPost = {
  slug: "daylight-and-hiking-season",
  status: "approved",
  publishedAt: "2026-09-30",
  modifiedAt: "2026-09-30",
  heroImageSlug: "lofotodden",
  evidence: [
    evidence("daylight-high-latitudes", "Annual minimum and maximum mean daylight for three high-latitude destinations.", [
      "public/data/hiking/destinations/no/lofotodden.json",
      "public/data/hiking/destinations/is/landmannalaugar.json",
      "public/data/hiking/destinations/us/denali.json",
    ]),
    evidence("daylight-equatorial", "Annual daylight ranges for three near-equatorial mountain destinations.", [
      "public/data/hiking/destinations/ug/rwenzori.json",
      "public/data/hiking/destinations/ke/mount-kenya.json",
      "public/data/hiking/destinations/ec/cotopaxi.json",
    ]),
  ],
  translations: {
    en: {
      title: "How daylight affects the best time to hike",
      description: "From 24-hour light in Lofotodden to an almost fixed 12-hour equatorial day, daylight reshapes the time available for a hike without describing the weather.",
      heroAlt: "Mountain and coastal landscape in Lofotodden National Park under northern light",
      category: "data-insight",
      readingMinutes: 8,
      blocks: [
        { type: "paragraph", text: "Temperature and rain usually lead a climate comparison, but daylight determines how much of a route can fit between dawn and dusk. That constraint changes dramatically with latitude. In the BestTimeToHike dataset, the selected point for Lofotodden ranges from 0.4 hours of mean daylight in its darkest month to 24.0 in its brightest. Near the equator, Rwenzori and Mount Kenya stay at about 12.1 hours through the year. Those figures do not say whether the sky is clear or whether a trail is safe. They describe the astronomical envelope within which every other decision must fit." },
        { type: "timeline", caption: "Annual daylight span at six representative points", points: [
          { label: "Lofotodden", value: "0.4–24.0 h", detail: "The widest span in this comparison" },
          { label: "Landmannalaugar", value: "4.4–20.7 h", detail: "Large Icelandic seasonal swing" },
          { label: "Denali", value: "4.6–20.5 h", detail: "Large Alaskan seasonal swing" },
          { label: "Cotopaxi", value: "12.1–12.2 h", detail: "Only one tenth of an hour across the year" },
          { label: "Rwenzori", value: "12.1 h", detail: "Stable in the published monthly values" },
          { label: "Mount Kenya", value: "12.1 h", detail: "Stable in the published monthly values" },
        ], evidenceKey: "daylight-high-latitudes" },
        { type: "heading", level: 2, text: "The northern arc: time expands and contracts" },
        { type: "paragraph", text: "Lofotodden's 23.6-hour annual span is the clearest example. A summer day can remove darkness as a scheduling limit, while winter offers almost none of the conventional daylight window. Landmannalaugar ranges from 4.4 to 20.7 hours, and Denali from 4.6 to 20.5. This does not automatically make the brightest month the best hiking month. Snow, temperature, precipitation and current access may still exclude or complicate it. It does mean that identical route distances create different planning problems. A long itinerary that fits easily into midsummer light may require a different start time, shorter objective or headlamp margin as the season turns." },
        { type: "comparisonTable", caption: "What the annual range changes, and what it does not", columns: ["Destination", "Minimum", "Maximum", "Daylight can inform", "Daylight cannot confirm"], rows: [
          { label: "Lofotodden", values: ["0.4 h", "24.0 h", "Available astronomical light", "Clear sky or route access"] },
          { label: "Landmannalaugar", values: ["4.4 h", "20.7 h", "Potential schedule length", "Road opening or snow state"] },
          { label: "Denali", values: ["4.6 h", "20.5 h", "Seasonal timing pressure", "Visibility or safe turnaround"] },
          { label: "Cotopaxi", values: ["12.1 h", "12.2 h", "Stable day length", "High-altitude conditions"] },
        ], evidenceKey: "daylight-equatorial" },
        { type: "paragraph", text: "The difference between daylight and usable hiking time is essential. Astronomical daylight is calculated from coordinates and date. Sunshine duration depends on cloud. Visibility depends on weather, terrain and vegetation. A steep valley can fall into shadow long before sunset, and polar summer can remain bright while fog erases useful visibility. The dataset therefore treats daylight as one component, not as a substitute for weather or route information. It is best used to compare seasonal scheduling pressure: how much theoretical light exists, how rapidly it is changing, and how large a safety margin the planned distance requires." },
        { type: "pullQuote", text: "Daylight sets the clock; weather and terrain decide how much of that clock is usable." },
        { type: "heading", level: 2, text: "The equatorial line: a stable clock, not a stable climate" },
        { type: "metricCallout", label: "Cotopaxi daylight range", value: "12.1 to 12.2 hours", detail: "The annual change is only 0.1 hour at the selected point, compared with 23.6 hours at Lofotodden.", evidenceKey: "daylight-equatorial" },
        { type: "paragraph", text: "Near-equatorial destinations invert the question. Rwenzori and Mount Kenya remain at roughly 12.1 hours in every published month, while Cotopaxi ranges only from 12.1 to 12.2. A traveller cannot use a longer summer day to compensate for a late start. The available light is predictable, but precipitation, cloud, temperature and high-altitude exposure can still vary. At these destinations, daylight contributes little to choosing one month over another; it contributes a consistent scheduling boundary. The planning emphasis moves toward rainfall patterns, temperature at the relevant elevation, acclimatisation and current official guidance." },
        { type: "heading", level: 2, text: "Turn the number into a route plan" },
        { type: "paragraph", text: "First compare the route's expected moving time with the month's mean daylight, then add time for breaks, navigation, slower terrain and an early turnaround. Second, check whether the route is shaded by mountains or forest and whether official advice recommends a particular start. Third, inspect current sunrise, sunset and weather for the exact trip date; a monthly historical mean is not precise enough for day-level timing. Finally, carry appropriate lighting even when the plan fits on paper. For high latitudes, also watch how quickly day length changes between weeks. For equatorial mountains, resist assuming that stable daylight means stable weather." },
        { type: "caveat", text: "Daylight values are deterministic astronomical monthly means based on the selected coordinates. They are not sunshine duration, visibility, civil-twilight guidance or safe walking hours. The climate figures still represent one model cell rather than each route. Current sunrise and sunset, route timing, access, weather and local safety information must be checked for the actual date." },
        { type: "destinationLinks", heading: "Explore both ends of the daylight range", links: [
          { label: "Lofotodden", href: links.destination("en", "lofotodden"), detail: "See the full 0.4 to 24.0-hour annual arc." },
          { label: "Landmannalaugar", href: links.destination("en", "landmannalaugar"), detail: "Compare Icelandic daylight with the short eligible season." },
          { label: "Denali", href: links.destination("en", "denali"), detail: "Inspect the Alaskan seasonal swing." },
          { label: "Rwenzori", href: links.destination("en", "rwenzori"), detail: "Read a near-equatorial 12.1-hour pattern." },
          { label: "Cotopaxi", href: links.destination("en", "cotopaxi"), detail: "Compare stable daylight with variable climate metrics." },
          { label: "Methodology", href: links.methodology("en"), detail: "Learn how daylight is calculated and scored." },
          { label: "Finder", href: links.finder("en"), detail: "Filter destinations by a minimum daylight preference." },
        ] },
      ],
    },
    de: {
      title: "Wie Tageslicht die beste Wanderzeit beeinflusst",
      description: "Von 24 Stunden Licht in Lofotodden bis zum fast festen Zwölfstundentag am Äquator: Tageslicht verändert die verfügbare Zeit, nicht das Wetter.",
      heroAlt: "Berg- und Küstenlandschaft im Lofotodden-Nationalpark unter nordischem Licht",
      category: "data-insight",
      readingMinutes: 9,
      blocks: [
        { type: "paragraph", text: "Temperatur und Regen führen meist einen Klimavergleich an, doch das Tageslicht bestimmt, wie viel Route zwischen Morgendämmerung und Dunkelheit Platz findet. Diese Grenze verändert sich mit der Breitenlage dramatisch. Im BestTimeToHike-Datensatz reicht der ausgewählte Punkt in Lofotodden von 0,4 Stunden mittlerem Tageslicht im dunkelsten bis zu 24,0 Stunden im hellsten Monat. In Äquatornähe bleiben Rwenzori und Mount Kenya ganzjährig bei ungefähr 12,1 Stunden. Diese Zahlen sagen weder etwas über einen klaren Himmel noch über die Sicherheit eines Weges. Sie beschreiben den astronomischen Rahmen, in den jede andere Entscheidung passen muss." },
        { type: "timeline", caption: "Jährliche Tageslichtspanne an sechs repräsentativen Punkten", points: [
          { label: "Lofotodden", value: "0,4–24,0 h", detail: "Die größte Spanne in diesem Vergleich" },
          { label: "Landmannalaugar", value: "4,4–20,7 h", detail: "Starker isländischer Jahresgang" },
          { label: "Denali", value: "4,6–20,5 h", detail: "Starker Jahresgang in Alaska" },
          { label: "Cotopaxi", value: "12,1–12,2 h", detail: "Nur eine Zehntelstunde im Jahresverlauf" },
          { label: "Rwenzori", value: "12,1 h", detail: "Stabil in den veröffentlichten Monatswerten" },
          { label: "Mount Kenya", value: "12,1 h", detail: "Stabil in den veröffentlichten Monatswerten" },
        ], evidenceKey: "daylight-high-latitudes" },
        { type: "heading", level: 2, text: "Der nördliche Bogen: Zeit dehnt sich und schrumpft" },
        { type: "paragraph", text: "Die jährliche Spanne von 23,6 Stunden in Lofotodden ist das deutlichste Beispiel. Ein Sommertag kann Dunkelheit als Zeitgrenze aufheben, während im Winter fast kein klassisches Tageslichtfenster bleibt. Landmannalaugar reicht von 4,4 bis 20,7 Stunden, Denali von 4,6 bis 20,5. Das macht den hellsten Monat nicht automatisch zum besten Wandermonat. Schnee, Temperatur, Niederschlag und aktueller Zugang können ihn weiterhin ausschließen oder erschweren. Gleiche Routendistanzen erzeugen aber verschiedene Planungsprobleme. Eine lange Strecke passt im Hochsommer leicht ins Licht und verlangt später einen früheren Start, ein kürzeres Ziel oder mehr Stirnlampenreserve." },
        { type: "comparisonTable", caption: "Was die Jahresspanne verändert und was nicht", columns: ["Ziel", "Minimum", "Maximum", "Tageslicht informiert über", "Tageslicht bestätigt nicht"], rows: [
          { label: "Lofotodden", values: ["0,4 h", "24,0 h", "Astronomisch verfügbares Licht", "Klaren Himmel oder Zugang"] },
          { label: "Landmannalaugar", values: ["4,4 h", "20,7 h", "Mögliche Zeitplanung", "Straßenöffnung oder Schneelage"] },
          { label: "Denali", values: ["4,6 h", "20,5 h", "Saisonalen Zeitdruck", "Sicht oder sichere Umkehrzeit"] },
          { label: "Cotopaxi", values: ["12,1 h", "12,2 h", "Stabile Tageslänge", "Hochgebirgsbedingungen"] },
        ], evidenceKey: "daylight-equatorial" },
        { type: "paragraph", text: "Der Unterschied zwischen Tageslicht und nutzbarer Wanderzeit ist entscheidend. Astronomisches Tageslicht wird aus Koordinaten und Datum berechnet. Sonnenscheindauer hängt von Wolken ab; Sicht von Wetter, Gelände und Vegetation. Ein steiles Tal kann lange vor Sonnenuntergang im Schatten liegen, während ein Polarsommertag hell bleibt und Nebel die brauchbare Sicht nimmt. Der Datensatz behandelt Tageslicht deshalb als eine Komponente und nicht als Ersatz für Wetter- oder Routeninformationen. Am besten eignet es sich zum Vergleich saisonalen Zeitdrucks: wie viel theoretisches Licht vorhanden ist, wie schnell es sich verändert und welche Reserve die geplante Distanz braucht." },
        { type: "pullQuote", text: "Tageslicht stellt die Uhr; Wetter und Gelände bestimmen, wie viel davon nutzbar ist." },
        { type: "heading", level: 2, text: "Die Äquatorlinie: stabile Uhr, nicht stabiles Klima" },
        { type: "metricCallout", label: "Tageslichtspanne am Cotopaxi", value: "12,1 bis 12,2 Stunden", detail: "Am ausgewählten Punkt verändert sich das Jahr nur um 0,1 Stunde, in Lofotodden dagegen um 23,6 Stunden.", evidenceKey: "daylight-equatorial" },
        { type: "paragraph", text: "Ziele in Äquatornähe kehren die Frage um. Rwenzori und Mount Kenya bleiben in jedem veröffentlichten Monat bei ungefähr 12,1 Stunden, Cotopaxi reicht nur von 12,1 bis 12,2. Ein längerer Sommertag kann einen späten Start nicht ausgleichen. Das verfügbare Licht ist vorhersehbar, doch Niederschlag, Wolken, Temperatur und Hochgebirgsexposition können sich weiterhin verändern. Hier trägt Tageslicht wenig zur Wahl zwischen Monaten bei; es setzt eine gleichmäßige Planungsgrenze. Der Schwerpunkt verschiebt sich auf Regenmuster, Temperatur in der relevanten Höhe, Akklimatisation und aktuelle offizielle Hinweise." },
        { type: "heading", level: 2, text: "Aus der Zahl einen Routenplan machen" },
        { type: "paragraph", text: "Zuerst die erwartete Gehzeit mit dem mittleren Tageslicht des Monats vergleichen und Pausen, Navigation, langsames Gelände sowie eine frühe Umkehr ergänzen. Danach prüfen, ob Berge oder Wald die Route beschatten und ob offizielle Hinweise eine Startzeit empfehlen. Anschließend aktuelle Sonnenauf- und -untergänge sowie das Wetter für das konkrete Datum ansehen; ein historisches Monatsmittel ist für Tagesplanung nicht genau genug. Geeignete Beleuchtung gehört trotzdem ins Gepäck. In hohen Breiten ist außerdem wichtig, wie rasch sich die Tageslänge innerhalb weniger Wochen ändert. In Äquatornähe darf stabiles Tageslicht nicht mit stabilem Wetter verwechselt werden." },
        { type: "caveat", text: "Die Tageslichtwerte sind deterministische astronomische Monatsmittel auf Basis der ausgewählten Koordinaten. Sie sind weder Sonnenscheindauer noch Sichtweite, Dämmerungshinweis oder sichere Gehzeit. Die Klimadaten repräsentieren weiterhin eine Modellzelle und nicht jede Route. Für das konkrete Datum müssen aktuelle Sonnenzeiten, Routenzeit, Zugang, Wetter und lokale Sicherheitshinweise geprüft werden." },
        { type: "destinationLinks", heading: "Beide Enden der Tageslichtspanne erkunden", links: [
          { label: "Lofotodden", href: links.destination("de", "lofotodden"), detail: "Den vollständigen Jahresbogen von 0,4 bis 24,0 Stunden ansehen." },
          { label: "Landmannalaugar", href: links.destination("de", "landmannalaugar"), detail: "Isländisches Tageslicht und kurze geeignete Saison vergleichen." },
          { label: "Denali", href: links.destination("de", "denali"), detail: "Den Jahresgang in Alaska prüfen." },
          { label: "Rwenzori", href: links.destination("de", "rwenzori"), detail: "Ein äquatornahes Muster mit 12,1 Stunden lesen." },
          { label: "Cotopaxi", href: links.destination("de", "cotopaxi"), detail: "Stabiles Tageslicht mit variablen Klimawerten vergleichen." },
          { label: "Methodik", href: links.methodology("de"), detail: "Nachlesen, wie Tageslicht berechnet und bewertet wird." },
          { label: "Finder", href: links.finder("de"), detail: "Ziele nach gewünschtem Mindesttageslicht filtern." },
        ] },
      ],
    },
  },
};
