import type { BlogPost } from "@/lib/blog/content";
import { links } from "@/lib/i18n/links";
import { evidence } from "./shared";

export const mildHikingAroundTheYear: BlogPost = {
  slug: "mild-hiking-around-the-year",
  status: "approved",
  publishedAt: "2026-09-30",
  modifiedAt: "2026-09-30",
  heroImageSlug: "madeira",
  evidence: [
    evidence("mild-year-itinerary", "Twelve recommendation-eligible destination-month pairs selected by an explicit temperature and wet-day rule.", [
      "public/data/hiking/destinations/dz/hoggar.json",
      "public/data/hiking/destinations/jo/wadi-rum.json",
      "public/data/hiking/destinations/mx/copper-canyon.json",
      "public/data/hiking/destinations/es/tenerife.json",
      "public/data/hiking/destinations/gr/samaria-crete.json",
      "public/data/hiking/destinations/pt/madeira.json",
      "public/data/hiking/destinations/au/larapinta.json",
      "public/data/hiking/destinations/us/mount-rainier.json",
      "public/data/hiking/destinations/us/sequoia-kings-canyon.json",
      "public/data/hiking/destinations/za/table-mountain.json",
      "public/data/hiking/destinations/ma/anti-atlas.json",
      "public/data/hiking/destinations/th/doi-inthanon.json",
    ]),
  ],
  translations: {
    en: {
      title: "A year of mild hiking: twelve months, twelve places",
      description: "An explicit climate rule builds a twelve-stop planning atlas, following historically mild hiking-hour temperatures without pretending to rank the world.",
      heroAlt: "Mountain trail on Madeira, the June stop in a twelve-month mild-climate hiking atlas",
      category: "planning",
      readingMinutes: 10,
      blocks: [
        { type: "paragraph", text: "Could a traveller follow mild hiking weather around the world for a full year? The question sounds like an invitation to produce a glossy top-twelve list. This atlas takes a stricter route. Every selected month must be recommendation-eligible in the current model, have a historical hiking-hour mean from 12 to 20 °C, and show no more than 25 percent wet days at the representative cell. Each destination may appear only once. The result is not the only valid itinerary and not a claim that these are the best places on Earth. It is one transparent answer generated from the same rules in every month." },
        { type: "monthStrip", caption: "The twelve-stop climate atlas", months: [
          { month: 1, label: "Jan · Hoggar Mountains", note: "13.0 °C · 1.94% wet", href: links.destinationMonth("en", "hoggar", 1) },
          { month: 2, label: "Feb · Wadi Rum", note: "13.2 °C · 7.29% wet", href: links.destinationMonth("en", "wadi-rum", 2) },
          { month: 3, label: "Mar · Copper Canyon", note: "14.7 °C · 9.49% wet", href: links.destinationMonth("en", "copper-canyon", 3) },
          { month: 4, label: "Apr · Tenerife", note: "13.8 °C · 13.05% wet", href: links.destinationMonth("en", "tenerife", 4) },
          { month: 5, label: "May · Samaria Gorge", note: "17.5 °C · 16.50% wet", href: links.destinationMonth("en", "samaria-crete", 5) },
          { month: 6, label: "Jun · Madeira", note: "18.7 °C · 17.52% wet", href: links.destinationMonth("en", "madeira", 6) },
          { month: 7, label: "Jul · Larapinta", note: "15.9 °C · 3.96% wet", href: links.destinationMonth("en", "larapinta", 7) },
          { month: 8, label: "Aug · Mount Rainier", note: "16.2 °C · 19.91% wet", href: links.destinationMonth("en", "mount-rainier", 8) },
          { month: 9, label: "Sep · Sequoia & Kings Canyon", note: "15.4 °C · 19.33% wet", href: links.destinationMonth("en", "sequoia-kings-canyon", 9) },
          { month: 10, label: "Oct · Table Mountain", note: "16.9 °C · 19.08% wet", href: links.destinationMonth("en", "table-mountain", 10) },
          { month: 11, label: "Nov · Anti-Atlas", note: "15.1 °C · 14.95% wet", href: links.destinationMonth("en", "anti-atlas", 11) },
          { month: 12, label: "Dec · Doi Inthanon", note: "19.5 °C · 13.64% wet", href: links.destinationMonth("en", "doi-inthanon", 12) },
        ], evidenceKey: "mild-year-itinerary" },
        { type: "heading", level: 2, text: "January to April: begin south, then turn north" },
        { type: "paragraph", text: "January starts in Algeria's Hoggar Mountains at 13.0 °C during the sampled hiking hours and 1.94 percent wet days. February moves to Wadi Rum, where 13.2 °C and 7.29 percent wet days create a cooler desert profile than its excluded midsummer months. March crosses to Mexico's Copper Canyon at 14.7 °C and 9.49 percent wet days. In April, Tenerife offers 13.8 °C and 13.05 percent. The geographic jumps are deliberate. Mild conditions do not march evenly northward; elevation, ocean influence and local seasonality create separate windows." },
        { type: "comparisonTable", caption: "The rule stays fixed while the landscapes change", columns: ["Quarter", "Stops", "Temperature span", "Wet-day span"], rows: [
          { label: "Jan–Mar", values: ["Hoggar, Wadi Rum, Copper Canyon", "13.0–14.7 °C", "1.94–9.49%"] },
          { label: "Apr–Jun", values: ["Tenerife, Samaria, Madeira", "13.8–18.7 °C", "13.05–17.52%"] },
          { label: "Jul–Sep", values: ["Larapinta, Rainier, Sequoia", "15.4–16.2 °C", "3.96–19.91%"] },
          { label: "Oct–Dec", values: ["Table Mountain, Anti-Atlas, Doi Inthanon", "15.1–19.5 °C", "13.64–19.08%"] },
        ], evidenceKey: "mild-year-itinerary" },
        { type: "heading", level: 2, text: "May to August: Mediterranean spring to mountain summer" },
        { type: "paragraph", text: "May's Samaria Gorge selection averages 17.5 °C with 16.50 percent wet days. June moves west to Madeira at 18.7 °C and 17.52 percent. July makes the largest climatic and geographic turn, to Australia's Larapinta Trail: 15.9 °C and only 3.96 percent wet days during Southern Hemisphere winter. August uses the short mountain window at Mount Rainier, where the representative cell has a 16.2 °C hiking-hour mean and 19.91 percent wet days. These are climate starting points, not route permissions. Gorge openings, desert water, wildfire, snowfields and park access require their own current checks." },
        { type: "timeline", caption: "September to December: following the transition again", points: [
          { label: "September", value: "Sequoia & Kings Canyon", detail: "15.4 °C · 19.33% wet" },
          { label: "October", value: "Table Mountain", detail: "16.9 °C · 19.08% wet" },
          { label: "November", value: "Anti-Atlas", detail: "15.1 °C · 14.95% wet" },
          { label: "December", value: "Doi Inthanon", detail: "19.5 °C · 13.64% wet" },
        ], evidenceKey: "mild-year-itinerary" },
        { type: "pullQuote", text: "The atlas ranks no destination; it demonstrates what one explicit preference rule produces." },
        { type: "paragraph", text: "The last four stops continue the same method. September selects Sequoia and Kings Canyon at 15.4 °C and 19.33 percent wet days. October crosses to South Africa's Table Mountain at 16.9 °C and 19.08 percent. November uses Morocco's Anti-Atlas at 15.1 °C and 14.95 percent, while December finishes on Doi Inthanon at 19.5 °C and 13.64 percent. None is interchangeable with the others. Daylight, elevation, remoteness and route character differ. The constant rule provides comparability, while the destination pages restore the context removed by a compact annual view." },
        { type: "heading", level: 2, text: "How to build your own version" },
        { type: "paragraph", text: "Change one rule at a time. A warmer preference could raise the lower temperature bound; a rain-sensitive traveller might lower the 25-percent ceiling. Fix travel months that cannot move, choose a region if long-haul jumps are unrealistic, and then inspect individual month pages. Do not optimise for the overall score alone. Read the physical metrics, selected elevation and caveats, then verify official access and current forecasts. The method is more valuable than this exact route because it makes personal trade-offs visible. Another traveller can apply different limits and produce an equally defensible calendar without copying a generic best-of list." },
        { type: "caveat", text: "The atlas uses 1991–2025 historical means and probabilities at one representative grid cell per destination. Its 12–20 °C and 25-percent wet-day limits are editorial selection rules for this article, not universal safety thresholds. Recommendation eligibility is a model result, not confirmation that a route is open. Distances, costs, visas, seasonality of services and travel emissions are outside this climate exercise." },
        { type: "destinationLinks", heading: "Start with a stop or build another year", links: [
          { label: "Hoggar Mountains", href: links.destination("en", "hoggar"), detail: "Explore the January starting point across all months." },
          { label: "Madeira", href: links.destination("en", "madeira"), detail: "Compare the June stop with the rest of its broad season." },
          { label: "Larapinta Trail", href: links.destination("en", "larapinta"), detail: "Read the July Southern Hemisphere winter profile." },
          { label: "Table Mountain", href: links.destination("en", "table-mountain"), detail: "Inspect the October stop and annual cycle." },
          { label: "Doi Inthanon", href: links.destination("en", "doi-inthanon"), detail: "Review the December endpoint." },
          { label: "Methodology", href: links.methodology("en"), detail: "Understand what eligibility and each metric mean." },
          { label: "Finder", href: links.finder("en"), detail: "Set your own month, temperature and rain preferences." },
        ] },
      ],
    },
    de: {
      title: "Ein Jahr mit mildem Wanderklima: zwölf Monate, zwölf Orte",
      description: "Eine klare Klimaregel erzeugt einen Atlas mit zwölf Stationen und folgt milden historischen Wandertemperaturen, ohne die Welt in eine Rangliste zu pressen.",
      heroAlt: "Bergweg auf Madeira, der Juni-Stopp in einem zwölfmonatigen Atlas mit mildem Wanderklima",
      category: "planning",
      readingMinutes: 11,
      blocks: [
        { type: "paragraph", text: "Kann eine Reise ein ganzes Jahr lang mildem Wanderwetter um die Welt folgen? Die Frage lädt zu einer glänzenden Top-Zwölf-Liste ein. Dieser Atlas wählt einen strengeren Weg. Jeder Monat muss im aktuellen Modell empfehlungsfähig sein, eine historische mittlere Temperatur von 12 bis 20 °C in den Wanderstunden besitzen und an der repräsentativen Zelle höchstens 25 Prozent nasse Tage zeigen. Jedes Ziel darf nur einmal vorkommen. Das Ergebnis ist weder die einzig gültige Route noch die Behauptung, dies seien die besten Orte der Erde. Es ist eine transparente Antwort, die in jedem Monat dieselben Regeln verwendet." },
        { type: "monthStrip", caption: "Der Klimaatlas mit zwölf Stationen", months: [
          { month: 1, label: "Jan · Hoggar-Gebirge", note: "13,0 °C · 1,94% nass", href: links.destinationMonth("de", "hoggar", 1) },
          { month: 2, label: "Feb · Wadi Rum", note: "13,2 °C · 7,29% nass", href: links.destinationMonth("de", "wadi-rum", 2) },
          { month: 3, label: "Mär · Copper Canyon", note: "14,7 °C · 9,49% nass", href: links.destinationMonth("de", "copper-canyon", 3) },
          { month: 4, label: "Apr · Teneriffa", note: "13,8 °C · 13,05% nass", href: links.destinationMonth("de", "tenerife", 4) },
          { month: 5, label: "Mai · Samaria", note: "17,5 °C · 16,50% nass", href: links.destinationMonth("de", "samaria-crete", 5) },
          { month: 6, label: "Jun · Madeira", note: "18,7 °C · 17,52% nass", href: links.destinationMonth("de", "madeira", 6) },
          { month: 7, label: "Jul · Larapinta", note: "15,9 °C · 3,96% nass", href: links.destinationMonth("de", "larapinta", 7) },
          { month: 8, label: "Aug · Mount Rainier", note: "16,2 °C · 19,91% nass", href: links.destinationMonth("de", "mount-rainier", 8) },
          { month: 9, label: "Sep · Sequoia & Kings Canyon", note: "15,4 °C · 19,33% nass", href: links.destinationMonth("de", "sequoia-kings-canyon", 9) },
          { month: 10, label: "Okt · Tafelberg", note: "16,9 °C · 19,08% nass", href: links.destinationMonth("de", "table-mountain", 10) },
          { month: 11, label: "Nov · Anti-Atlas", note: "15,1 °C · 14,95% nass", href: links.destinationMonth("de", "anti-atlas", 11) },
          { month: 12, label: "Dez · Doi Inthanon", note: "19,5 °C · 13,64% nass", href: links.destinationMonth("de", "doi-inthanon", 12) },
        ], evidenceKey: "mild-year-itinerary" },
        { type: "heading", level: 2, text: "Januar bis April: im Süden beginnen, dann nach Norden" },
        { type: "paragraph", text: "Der Januar startet im algerischen Hoggar-Gebirge bei 13,0 °C während der untersuchten Wanderstunden und 1,94 Prozent nassen Tagen. Im Februar folgt Wadi Rum mit 13,2 °C und 7,29 Prozent nassen Tagen, ein kühleres Wüstenprofil als in den ausgeschlossenen Hochsommermonaten. Im März geht es zum mexikanischen Copper Canyon bei 14,7 °C und 9,49 Prozent nassen Tagen. Im April bietet Teneriffa 13,8 °C und 13,05 Prozent. Die geografischen Sprünge sind Absicht. Milde Bedingungen wandern nicht gleichmäßig nach Norden; Höhe, Ozeaneinfluss und lokale Saisonalität erzeugen getrennte Fenster." },
        { type: "comparisonTable", caption: "Die Regel bleibt gleich, die Landschaften wechseln", columns: ["Quartal", "Stationen", "Temperaturspanne", "Spanne nasser Tage"], rows: [
          { label: "Jan–Mär", values: ["Hoggar, Wadi Rum, Copper Canyon", "13,0–14,7 °C", "1,94–9,49%"] },
          { label: "Apr–Jun", values: ["Teneriffa, Samaria, Madeira", "13,6–18,7 °C", "13,22–16,67%"] },
          { label: "Jul–Sep", values: ["Larapinta, Rainier, Sequoia", "15,3–16,0 °C", "4,09–19,78%"] },
          { label: "Okt–Dez", values: ["Tafelberg, Anti-Atlas, Doi Inthanon", "14,8–19,4 °C", "14,19–19,78%"] },
        ], evidenceKey: "mild-year-itinerary" },
        { type: "heading", level: 2, text: "Mai bis August: vom Mittelmeerfrühling zum Bergsommer" },
        { type: "paragraph", text: "Die Samaria-Schlucht erreicht im Mai 17,5 °C und 16,50 Prozent nasse Tage. Im Juni geht es westwärts nach Madeira mit 18,7 °C und 17,52 Prozent. Der Juli bringt den größten klimatischen und geografischen Wechsel zum australischen Larapinta Trail: 15,9 °C und nur 3,96 Prozent nasse Tage im Winter der Südhalbkugel. Im August nutzt der Atlas das kurze Bergfenster am Mount Rainier, dessen repräsentative Zelle 16,2 °C und 19,91 Prozent nasse Tage zeigt. Das sind klimatische Ausgangspunkte und keine Routengenehmigungen. Schluchtöffnungen, Wüstenwasser, Waldbrand, Schneefelder und Parkzugang brauchen eigene aktuelle Prüfungen." },
        { type: "timeline", caption: "September bis Dezember: erneut dem Übergang folgen", points: [
          { label: "September", value: "Sequoia & Kings Canyon", detail: "15,4 °C · 19,33% nass" },
          { label: "Oktober", value: "Tafelberg", detail: "16,9 °C · 19,08% nass" },
          { label: "November", value: "Anti-Atlas", detail: "15,1 °C · 14,95% nass" },
          { label: "Dezember", value: "Doi Inthanon", detail: "19,5 °C · 13,64% nass" },
        ], evidenceKey: "mild-year-itinerary" },
        { type: "pullQuote", text: "Der Atlas ordnet kein Ziel ein; er zeigt, was eine ausdrücklich genannte Vorliebenregel hervorbringt." },
        { type: "paragraph", text: "Die letzten vier Stationen folgen derselben Methode. Im September stehen Sequoia & Kings Canyon bei 15,4 °C und 19,33 Prozent nassen Tagen. Der Oktober wechselt zum südafrikanischen Tafelberg bei 16,9 °C und 19,08 Prozent. Im November folgt der marokkanische Anti-Atlas bei 15,1 °C und 14,95 Prozent; der Dezember endet am Doi Inthanon bei 19,5 °C und 13,64 Prozent. Kein Ziel ist mit einem anderen austauschbar. Tageslicht, Höhe, Abgeschiedenheit und Wegcharakter unterscheiden sich. Die konstante Regel schafft Vergleichbarkeit, die Zielseiten bringen den Kontext zurück, den ein kompakter Jahresblick entfernt." },
        { type: "heading", level: 2, text: "Eine eigene Version bauen" },
        { type: "paragraph", text: "Immer nur eine Regel verändern. Wer es wärmer mag, kann die untere Temperaturgrenze anheben; regenempfindliche Reisende können die Grenze von 25 Prozent senken. Unverrückbare Reisemonate festlegen, bei unrealistischen Langstreckensprüngen eine Region wählen und anschließend einzelne Monatsseiten prüfen. Nicht allein den Gesamtscore optimieren. Physikalische Kennzahlen, ausgewählte Höhe und Hinweise lesen, dann offiziellen Zugang und aktuelle Vorhersagen prüfen. Die Methode ist wertvoller als diese genaue Route, weil sie persönliche Abwägungen sichtbar macht. Andere Grenzen können einen ebenso begründbaren Kalender ergeben, ohne eine generische Bestenliste zu kopieren." },
        { type: "caveat", text: "Der Atlas verwendet historische Mittelwerte und Wahrscheinlichkeiten von 1991 bis 2025 an einer repräsentativen Gitterzelle je Ziel. Seine Grenzen von 12–20 °C und 25 Prozent nassen Tagen sind redaktionelle Auswahlregeln dieses Artikels und keine universellen Sicherheitsgrenzen. Empfehlungsfähigkeit bestätigt keine Wegöffnung. Distanzen, Kosten, Visa, saisonale Dienste und Reiseemissionen liegen außerhalb dieser Klimaübung." },
        { type: "destinationLinks", heading: "Mit einer Station beginnen oder ein anderes Jahr bauen", links: [
          { label: "Hoggar-Gebirge", href: links.destination("de", "hoggar"), detail: "Den Januarstart über alle Monate vergleichen." },
          { label: "Madeira", href: links.destination("de", "madeira"), detail: "Den Junistopp mit der übrigen breiten Saison vergleichen." },
          { label: "Larapinta Trail", href: links.destination("de", "larapinta"), detail: "Das Profil des südlichen Winters im Juli lesen." },
          { label: "Tafelberg", href: links.destination("de", "table-mountain"), detail: "Oktoberstopp und Jahresgang prüfen." },
          { label: "Doi Inthanon", href: links.destination("de", "doi-inthanon"), detail: "Den Endpunkt im Dezember ansehen." },
          { label: "Methodik", href: links.methodology("de"), detail: "Verstehen, was Empfehlungsfähigkeit und Kennzahlen bedeuten." },
          { label: "Finder", href: links.finder("de"), detail: "Eigene Monats-, Temperatur- und Regenvorlieben setzen." },
        ] },
      ],
    },
  },
};
