import type { BlogPost } from "@/lib/blog/content";
import { links } from "@/lib/i18n/links";
import { evidence } from "./shared";

export const shoulderSeasonHikingWorldwide: BlogPost = {
  slug: "shoulder-season-hiking-worldwide",
  status: "approved",
  publishedAt: "2026-09-30",
  modifiedAt: "2026-09-30",
  heroImageSlug: "samaria-crete",
  evidence: [
    evidence("shoulder-season-north", "May and September historical conditions for three Northern Hemisphere destinations.", [
      "public/data/hiking/destinations/es/tenerife.json",
      "public/data/hiking/destinations/gr/samaria-crete.json",
      "public/data/hiking/destinations/us/sequoia-kings-canyon.json",
    ]),
    evidence("shoulder-season-south", "March and October historical conditions for two Southern Hemisphere destinations.", [
      "public/data/hiking/destinations/au/grampians.json",
      "public/data/hiking/destinations/za/cederberg.json",
    ]),
  ],
  translations: {
    en: {
      title: "Best shoulder-season hiking months around the world",
      description: "Five historical climate profiles show why spring and autumn are directions on a globe, not fixed months on a universal hiking calendar.",
      heroAlt: "Rocky trail landscape in Samaria Gorge, used in the Northern Hemisphere shoulder-season comparison",
      category: "planning",
      readingMinutes: 8,
      blocks: [
        { type: "paragraph", text: "Shoulder season is often presented as a bargain between summer and winter: milder temperatures, fewer visitors and a chance of unsettled weather. The phrase becomes less useful as soon as a trip crosses the equator. May is late spring around the Mediterranean, while March is early autumn in southern Australia. September can open a cooler window in California as October lengthens the Southern Hemisphere day. Instead of naming one global shoulder season, this guide follows five destination-month pairs whose historical temperature, wet-day share and daylight form a plausible starting point for hiking research. It is a field guide to transitions, not a ranking of the world's best months." },
        { type: "timeline", caption: "A seasonal path across the two hemispheres", points: [
          { label: "March, Grampians", value: "18.6 °C · 15.67% wet · 12.3 h", detail: "Southern Hemisphere autumn" },
          { label: "May, Tenerife", value: "16.0 °C · 5.62% wet · 13.6 h", detail: "Northern Hemisphere late spring" },
          { label: "May, Samaria Gorge", value: "17.5 °C · 16.50% wet · 14.0 h", detail: "Mediterranean transition toward summer" },
          { label: "September, Sequoia & Kings Canyon", value: "15.4 °C · 19.33% wet · 12.4 h", detail: "Northern Hemisphere early autumn" },
          { label: "October, Cederberg", value: "19.4 °C · 15.94% wet · 12.9 h", detail: "Southern Hemisphere spring" },
        ], evidenceKey: "shoulder-season-north" },
        { type: "heading", level: 2, text: "North: two versions of spring and one of autumn" },
        { type: "paragraph", text: "Tenerife in May combines a 16.0 °C mean during sampled hiking hours with 5.62 percent wet days and 13.6 hours of mean daylight. Samaria Gorge in the same month is warmer at 17.5 °C, has 16.50 percent wet days and receives about 14.0 hours of daylight. Those numbers suggest two different spring decisions: Tenerife offers the drier representative-cell history, while Samaria offers a slightly warmer profile. Neither number describes every elevation or confirms route access. In September, Sequoia and Kings Canyon has a 15.4 °C hiking-hour mean, 19.33 percent wet days and 12.4 daylight hours, a different balance as the northern summer recedes." },
        { type: "comparisonTable", caption: "Five transitions, viewed through the same three metrics", columns: ["Destination and month", "Hiking-hour mean", "Wet days", "Daylight"], rows: [
          { label: "Grampians, March", values: ["18.6 °C", "15.67%", "12.3 h"] },
          { label: "Tenerife, May", values: ["16.0 °C", "5.62%", "13.6 h"] },
          { label: "Samaria Gorge, May", values: ["17.5 °C", "16.50%", "14.0 h"] },
          { label: "Sequoia & Kings Canyon, September", values: ["15.4 °C", "19.33%", "12.4 h"] },
          { label: "Cederberg, October", values: ["19.4 °C", "15.94%", "12.9 h"] },
        ], evidenceKey: "shoulder-season-south" },
        { type: "pullQuote", text: "Shoulder season describes a transition; the useful month depends on latitude, hemisphere and elevation." },
        { type: "heading", level: 2, text: "South: autumn in March, spring in October" },
        { type: "paragraph", text: "The Grampians in March supply a Southern Hemisphere autumn example: 18.6 °C in the sampled hiking window, 15.67 percent wet days and 12.3 hours of daylight. Cederberg in October illustrates the spring side of the cool season. Its selected cell averages 19.4 °C, 15.94 percent wet days and 12.9 hours of daylight. The figures are attractive, but the two destinations are not interchangeable. They occupy different terrain and elevations, and dry rocky landscapes introduce exposure, water and temperature-range questions that a monthly mean cannot settle. The comparison identifies climate candidates, not equivalent hiking experiences." },
        { type: "metricCallout", label: "The hemisphere check", value: "May north ≠ May south", detail: "A month name does not carry a season with it. Read the destination's latitude, local seasonal direction and daylight before using a shoulder-season label.", evidenceKey: "shoulder-season-south" },
        { type: "paragraph", text: "Daylight is especially useful as a planning constraint because it changes what can fit into a day, yet it must not be confused with sunshine. Fourteen astronomical daylight hours in Samaria do not promise fourteen clear hours, and 12.9 hours in Cederberg do not guarantee a safe amount of usable trail time. Cloud, terrain shadow, start times, heat and the route's pace all reduce the practical window. Wet-day probability also needs careful language: it is the historical share of days meeting the dataset's wet-day definition at the representative cell, not the chance that a particular future hike will receive rain." },
        { type: "heading", level: 2, text: "Build a shortlist, then localise it" },
        { type: "paragraph", text: "A practical workflow begins with the month you can travel. Identify which hemisphere is moving toward or away from summer, then compare temperature, wet-day share and daylight together. Remove months that fail a critical gate. Next, inspect the selected elevation and ask whether your intended route sits much higher or lower. Finally, check current local forecasts, park or trail information, transport and seasonal services. This sequence prevents two common mistakes: treating a pleasant regional average as route-specific evidence, and treating shoulder season as a universal promise of quiet, mild weather. The historical data is most valuable when it narrows the search while leaving the final decision open to current evidence." },
        { type: "caveat", text: "All figures are 1991–2025 historical values for one selected representative ERA5-Land cell per destination. They are not forecasts, visitor-level estimates or statements about trail openings. Daylight is an astronomical mean rather than sunshine duration. Elevation, terrain and local microclimates can produce conditions unlike the representative point, so official and current sources remain necessary." },
        { type: "destinationLinks", heading: "Follow each seasonal transition", links: [
          { label: "Tenerife", href: links.destinationMonth("en", "tenerife", 5), detail: "Read the full May climate profile." },
          { label: "Samaria Gorge", href: links.destinationMonth("en", "samaria-crete", 5), detail: "Compare a warmer Mediterranean May." },
          { label: "Grampians", href: links.destinationMonth("en", "grampians", 3), detail: "See the March Southern Hemisphere transition." },
          { label: "Sequoia & Kings Canyon", href: links.destinationMonth("en", "sequoia-kings-canyon", 9), detail: "Inspect the September representative-cell metrics." },
          { label: "Cederberg", href: links.destinationMonth("en", "cederberg", 10), detail: "Explore the October spring profile." },
          { label: "Methodology", href: links.methodology("en"), detail: "Understand metric definitions and limits." },
          { label: "Finder", href: links.finder("en"), detail: "Build a month-specific shortlist across regions." },
        ] },
      ],
    },
    de: {
      title: "Die besten Monate zum Wandern in der Nebensaison",
      description: "Fünf historische Klimaprofile zeigen, warum Frühling und Herbst Richtungen auf dem Globus sind und keine festen Monate im Weltkalender.",
      heroAlt: "Felsige Wanderlandschaft in der Samaria-Schlucht für den Vergleich der nördlichen Nebensaison",
      category: "planning",
      readingMinutes: 9,
      blocks: [
        { type: "paragraph", text: "Die Nebensaison gilt oft als Kompromiss zwischen Sommer und Winter: mildere Temperaturen, weniger Besucher und möglicherweise wechselhaftes Wetter. Sobald eine Reise den Äquator überquert, verliert der Begriff an Klarheit. Der Mai ist am Mittelmeer später Frühling, während der März im Süden Australiens frühen Herbst bedeutet. Der September kann in Kalifornien ein kühleres Fenster öffnen, während im Oktober die Tage auf der Südhalbkugel länger werden. Statt eine weltweite Nebensaison auszurufen, folgt dieser Leitfaden fünf Ziel-Monat-Paaren, deren historische Temperatur, Anteil nasser Tage und Tageslicht einen plausiblen Ausgangspunkt bilden. Es ist ein Wegweiser durch Übergänge, keine Weltrangliste." },
        { type: "timeline", caption: "Ein saisonaler Weg über beide Hemisphären", points: [
          { label: "März, Grampians", value: "18,6 °C · 15,67% nass · 12,3 h", detail: "Herbst auf der Südhalbkugel" },
          { label: "Mai, Teneriffa", value: "16,0 °C · 5,62% nass · 13,6 h", detail: "Später Frühling auf der Nordhalbkugel" },
          { label: "Mai, Samaria-Schlucht", value: "17,5 °C · 16,50% nass · 14,0 h", detail: "Mediterraner Übergang zum Sommer" },
          { label: "September, Sequoia & Kings Canyon", value: "15,4 °C · 19,33% nass · 12,4 h", detail: "Früher Herbst auf der Nordhalbkugel" },
          { label: "Oktober, Cederberg", value: "19,4 °C · 15,94% nass · 12,9 h", detail: "Frühling auf der Südhalbkugel" },
        ], evidenceKey: "shoulder-season-north" },
        { type: "heading", level: 2, text: "Norden: zwei Formen des Frühlings und eine des Herbstes" },
        { type: "paragraph", text: "Teneriffa verbindet im Mai 16,0 °C mittlere Temperatur während der untersuchten Wanderstunden mit 5,62 Prozent nassen Tagen und 13,6 Stunden mittlerem Tageslicht. Die Samaria-Schlucht ist im selben Monat mit 17,5 °C wärmer, erreicht 16,50 Prozent nasse Tage und ungefähr 14,0 Stunden Tageslicht. Daraus ergeben sich zwei verschiedene Frühlingsentscheidungen: Teneriffa hat an der ausgewählten Zelle die trockenere Historie, Samaria das etwas wärmere Profil. Keine Zahl beschreibt jede Höhenlage oder bestätigt den Routenzugang. Im September erreicht Sequoia & Kings Canyon 15,4 °C, 19,33 Prozent nasse Tage und 12,4 Stunden Licht, ein anderer Ausgleich beim Rückzug des Nordsommers." },
        { type: "comparisonTable", caption: "Fünf Übergänge mit denselben drei Kennzahlen", columns: ["Ziel und Monat", "Mittel in Wanderstunden", "Nasse Tage", "Tageslicht"], rows: [
          { label: "Grampians, März", values: ["18,6 °C", "15,67%", "12,3 h"] },
          { label: "Teneriffa, Mai", values: ["16,0 °C", "5,62%", "13,6 h"] },
          { label: "Samaria-Schlucht, Mai", values: ["17,5 °C", "16,50%", "14,0 h"] },
          { label: "Sequoia & Kings Canyon, September", values: ["15,4 °C", "19,33%", "12,4 h"] },
          { label: "Cederberg, Oktober", values: ["19,4 °C", "15,94%", "12,9 h"] },
        ], evidenceKey: "shoulder-season-south" },
        { type: "pullQuote", text: "Nebensaison bezeichnet einen Übergang; der nützliche Monat hängt von Breite, Hemisphäre und Höhe ab." },
        { type: "heading", level: 2, text: "Süden: Herbst im März, Frühling im Oktober" },
        { type: "paragraph", text: "Die Grampians liefern im März ein Beispiel für den südlichen Herbst: 18,6 °C im untersuchten Wanderfenster, 15,67 Prozent nasse Tage und 12,3 Stunden Tageslicht. Cederberg zeigt im Oktober die Frühlingsseite der kühlen Jahreshälfte. Die ausgewählte Zelle erreicht 19,4 °C, 15,94 Prozent nasse Tage und 12,9 Stunden Tageslicht. Die Werte wirken attraktiv, doch die Ziele sind nicht austauschbar. Gelände und Höhenlage unterscheiden sich, und trockene Felslandschaften bringen Fragen zu Exposition, Wasser und Temperaturspanne mit, die ein Monatsmittel nicht klärt. Der Vergleich findet Klimakandidaten, keine identischen Wandererlebnisse." },
        { type: "metricCallout", label: "Der Hemisphären-Check", value: "Mai im Norden ≠ Mai im Süden", detail: "Ein Monatsname trägt keine Jahreszeit in sich. Vor dem Begriff Nebensaison müssen Breitenlage, lokale saisonale Richtung und Tageslicht gelesen werden.", evidenceKey: "shoulder-season-south" },
        { type: "paragraph", text: "Tageslicht ist als Planungsgrenze besonders hilfreich, darf aber nicht mit Sonnenschein verwechselt werden. Vierzehn astronomische Tageslichtstunden in Samaria versprechen keine vierzehn wolkenfreien Stunden; 12,9 Stunden in Cederberg garantieren keine sichere nutzbare Gehzeit. Wolken, Geländeschatten, Startzeit, Hitze und Routentempo verkürzen das praktische Fenster. Auch die Wahrscheinlichkeit nasser Tage braucht präzise Sprache: Sie ist der historische Anteil der Tage, die an der repräsentativen Zelle die Definition des Datensatzes erfüllen, nicht die Regenwahrscheinlichkeit für eine bestimmte zukünftige Tour." },
        { type: "heading", level: 2, text: "Eine Auswahl bauen und anschließend lokalisieren" },
        { type: "paragraph", text: "Ein sinnvoller Ablauf beginnt mit dem möglichen Reisemonat. Zuerst prüfen, welche Hemisphäre sich auf den Sommer zubewegt oder von ihm entfernt, dann Temperatur, Anteil nasser Tage und Tageslicht gemeinsam vergleichen. Monate mit kritischem Gate ausschließen. Danach die ausgewählte Modellhöhe ansehen und fragen, ob die geplante Route viel höher oder tiefer liegt. Zum Schluss folgen aktuelle lokale Vorhersagen, Park- und Weghinweise, Transport und saisonale Dienste. So werden zwei typische Fehler vermieden: ein angenehmes Regionsmittel als routenspezifische Evidenz zu behandeln und Nebensaison als weltweites Versprechen ruhigen, milden Wetters zu verstehen." },
        { type: "caveat", text: "Alle Zahlen sind historische Werte von 1991 bis 2025 für eine ausgewählte repräsentative ERA5-Land-Zelle je Ziel. Sie sind weder Vorhersage noch Besucherstatistik oder Aussage zu Wegöffnungen. Tageslicht ist ein astronomisches Mittel und keine Sonnenscheindauer. Höhe, Gelände und lokale Mikroklimata können vom repräsentativen Punkt abweichen, deshalb bleiben offizielle und aktuelle Quellen erforderlich." },
        { type: "destinationLinks", heading: "Den saisonalen Übergängen folgen", links: [
          { label: "Teneriffa", href: links.destinationMonth("de", "tenerife", 5), detail: "Das vollständige Klimaprofil für Mai lesen." },
          { label: "Samaria-Schlucht", href: links.destinationMonth("de", "samaria-crete", 5), detail: "Einen wärmeren mediterranen Mai vergleichen." },
          { label: "Grampians", href: links.destinationMonth("de", "grampians", 3), detail: "Den südlichen Übergang im März ansehen." },
          { label: "Sequoia & Kings Canyon", href: links.destinationMonth("de", "sequoia-kings-canyon", 9), detail: "Die Kennzahlen der Septemberzelle prüfen." },
          { label: "Cederberg", href: links.destinationMonth("de", "cederberg", 10), detail: "Das Frühlingsprofil im Oktober erkunden." },
          { label: "Methodik", href: links.methodology("de"), detail: "Definitionen und Grenzen der Kennzahlen verstehen." },
          { label: "Finder", href: links.finder("de"), detail: "Eine monatsspezifische Auswahl über Regionen bauen." },
        ] },
      ],
    },
  },
};
